# -*- coding: utf-8 -*-
"""Assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJgAsJGd9DXFGl9-IpoUs0cHtTjKh1EJ
"""

#Nama : Tia Fiendi A
#NIM : 1101204055

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("data0-SZL.csv")

statistics_df = pd.DataFrame()

for column in df.columns:
    statistics_df[f'{column}_mean'] = [df[column].mean()]
    statistics_df[f'{column}_std'] = [df[column].std()]
    statistics_df[f'{column}_skew'] = [df[column].skew()]
    statistics_df[f'{column}_median'] = [df[column].median()]
    statistics_df[f'{column}_energy'] = [np.sum(df[column]**2)]
    statistics_df[f'{column}_min'] = [df[column].min()]
    statistics_df[f'{column}_max'] = [df[column].max()]

selected_columns = np.random.choice(df.columns, 6, replace=False)
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

for i, ax in enumerate(axes.flat):
    column = selected_columns[i]
    ax.plot(df[column])
    ax.set_title(column)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 8))

for i in range(0, 30, 10):
    plt.scatter(statistics_df.iloc[:, i], statistics_df.iloc[:, i + 1], label=f'Column {i+1}-{i+10}')

plt.xlabel('Mean')
plt.ylabel('Standard Deviation')
plt.legend()
plt.show()

plt.figure(figsize=(10, 8))

for i in range(0, 30, 10):
    plt.scatter(statistics_df.iloc[:, i + 2], statistics_df.iloc[:, i + 3], label=f'Column {i+1}-{i+10}')

plt.xlabel('Skewness')
plt.ylabel('Median')
plt.legend()
plt.show()